PRODUCTS = [
    {
        "id": "1",
        "title": "Wireless Keyboard",
        "description": "Compact and rechargeable wireless keyboard",
        "price": 49.99,
    },
    {
        "id": "2",
        "title": "Gaming Mouse",
        "description": "High precision gaming mouse with RGB lighting",
        "price": 29.99,
    },
    {
        "id": "3",
        "title": "Mechanical Keyboard",
        "description": "Mechanical keyboard with blue switches",
        "price": 89.99,
    },
    {
        "id": "4",
        "title": "Noise Cancelling Headphones",
        "description": "Wireless noise-cancelling over-ear headphones",
        "price": 199.99,
    },
    {
        "id": "5",
        "title": "4K Monitor",
        "description": "27-inch 4K UHD monitor with HDR",
        "price": 349.99,
    },
    {
        "id": "6",
        "title": "External SSD 1TB",
        "description": "High-speed portable SSD with USB-C",
        "price": 129.99,
    },
    {
        "id": "7",
        "title": "USB-C Docking Station",
        "description": "Multi-port docking station with HDMI and Ethernet",
        "price": 79.99,
    },
    {
        "id": "8",
        "title": "Smartwatch",
        "description": "Fitness tracking smartwatch with heart rate monitor",
        "price": 149.99,
    },
    {
        "id": "9",
        "title": "Wireless Earbuds",
        "description": "Bluetooth wireless earbuds with noise isolation",
        "price": 59.99,
    },
    {
        "id": "10",
        "title": "Laptop Stand",
        "description": "Adjustable aluminum laptop stand for ergonomic use",
        "price": 39.99,
    },
    {
        "id": "11",
        "title": "Bluetooth Speaker",
        "description": "Waterproof Bluetooth speaker with deep bass",
        "price": 69.99,
    },
    {
        "id": "12",
        "title": "Webcam 1080p",
        "description": "Full HD 1080p webcam with built-in microphone",
        "price": 49.99,
    },
    {
        "id": "13",
        "title": "Graphic Tablet",
        "description": "Drawing tablet with pressure sensitivity",
        "price": 129.99,
    },
    {
        "id": "14",
        "title": "Portable Projector",
        "description": "Mini projector with Wi-Fi and HDMI support",
        "price": 199.99,
    },
    {
        "id": "15",
        "title": "Smart LED Light Strip",
        "description": "RGB smart LED light strip with app control",
        "price": 24.99,
    },
]
